create table if not exists public.bible_state (
  user_id uuid not null references auth.users (id) on delete cascade,
  key text not null,
  value jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, key)
);

create table if not exists public.favorite_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  verse_text text not null default '',
  created_at text not null default '',
  primary key (user_id, book_code, chapter, verse)
);

create table if not exists public.memos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  title text not null default '',
  content text not null default '',
  verse_text text not null default '',
  created_at text not null default ''
);

alter table public.memos add column if not exists client_id text;

create index if not exists memos_user_id_created_at_idx
  on public.memos (user_id, created_at desc, id desc);

create unique index if not exists memos_user_id_client_id_idx
  on public.memos (user_id, client_id)
  where client_id is not null;

create table if not exists public.memo_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  memo_id bigint not null references public.memos (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  primary key (user_id, memo_id, book_code, chapter, verse)
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  plan_name text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  total_read_count integer not null default 0,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  goal_status jsonb not null default '[]'::jsonb,
  selected_book_codes jsonb not null default '[]'::jsonb,
  created_at text not null default '',
  updated_at text not null default ''
);

alter table public.plans add column if not exists client_id text;

create index if not exists plans_user_id_idx
  on public.plans (user_id, id desc);

create unique index if not exists plans_user_id_client_id_idx
  on public.plans (user_id, client_id)
  where client_id is not null;

create table if not exists public.prayers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  requester text not null default '',
  target text not null default '',
  created_at text not null default ''
);

alter table public.prayers add column if not exists client_id text;

create unique index if not exists prayers_user_id_client_id_idx
  on public.prayers (user_id, client_id)
  where client_id is not null;

create table if not exists public.prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.prayers (id) on delete cascade,
  client_id text,
  content text not null default '',
  registered_at text not null default ''
);

alter table public.prayer_contents add column if not exists client_id text;

drop index if exists public.prayer_contents_user_id_prayer_id_idx;
drop index if exists public.prayer_contents_user_id_client_id_idx;

create index if not exists prayer_contents_prayer_id_registered_at_idx
  on public.prayer_contents (prayer_id, registered_at desc, id desc);

create unique index if not exists prayer_contents_prayer_id_client_id_idx
  on public.prayer_contents (prayer_id, client_id)
  where client_id is not null;

create table if not exists public.bible_grass (
  user_id uuid not null references auth.users (id) on delete cascade,
  date text not null,
  data jsonb not null default '[]'::jsonb,
  primary key (user_id, date)
);

alter table public.bible_state enable row level security;
alter table public.favorite_verses enable row level security;
alter table public.memos enable row level security;
alter table public.memo_verses enable row level security;
alter table public.plans enable row level security;
alter table public.prayers enable row level security;
alter table public.prayer_contents enable row level security;
alter table public.bible_grass enable row level security;

drop policy if exists "bible_state_owner" on public.bible_state;
create policy "bible_state_owner"
  on public.bible_state
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "favorite_verses_owner" on public.favorite_verses;
create policy "favorite_verses_owner"
  on public.favorite_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memos_owner" on public.memos;
create policy "memos_owner"
  on public.memos
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memo_verses_owner" on public.memo_verses;
create policy "memo_verses_owner"
  on public.memo_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "plans_owner" on public.plans;
create policy "plans_owner"
  on public.plans
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "prayers_owner" on public.prayers;
create policy "prayers_owner"
  on public.prayers
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "prayer_contents_owner" on public.prayer_contents;
create policy "prayer_contents_owner"
  on public.prayer_contents
  for all
  using (
    exists (
      select 1
      from public.prayers
      where prayers.id = prayer_contents.prayer_id
        and prayers.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.prayers
      where prayers.id = prayer_contents.prayer_id
        and prayers.user_id = auth.uid()
    )
  );

drop policy if exists "bible_grass_owner" on public.bible_grass;
create policy "bible_grass_owner"
  on public.bible_grass
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
