create table if not exists public.user_bible_state (
  user_id uuid not null references auth.users (id) on delete cascade,
  key text not null,
  value jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, key)
);

create table if not exists public.user_favorite_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  verse_text text not null default '',
  created_at text not null default '',
  primary key (user_id, book_code, chapter, verse)
);

create table if not exists public.user_memos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  title text not null default '',
  content text not null default '',
  verse_text text not null default '',
  created_at text not null default ''
);

alter table public.user_memos add column if not exists client_id text;

create index if not exists user_memos_user_id_created_at_idx
  on public.user_memos (user_id, created_at desc, id desc);

create unique index if not exists user_memos_user_id_client_id_idx
  on public.user_memos (user_id, client_id)
  where client_id is not null;

create table if not exists public.user_memo_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  memo_id bigint not null references public.user_memos (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  primary key (user_id, memo_id, book_code, chapter, verse)
);

create table if not exists public.user_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  plan_name text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  total_read_count integer not null default 0,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  goal_status jsonb not null default '[]'::jsonb,
  selected_book_codes jsonb not null default '[]'::jsonb,
  created_at text not null default '',
  updated_at text not null default ''
);

alter table public.user_plans add column if not exists client_id text;

create index if not exists user_plans_user_id_idx
  on public.user_plans (user_id, id desc);

create unique index if not exists user_plans_user_id_client_id_idx
  on public.user_plans (user_id, client_id)
  where client_id is not null;

create table if not exists public.user_prayers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  requester text not null default '',
  target text not null default '',
  created_at text not null default ''
);

alter table public.user_prayers add column if not exists client_id text;

create unique index if not exists user_prayers_user_id_client_id_idx
  on public.user_prayers (user_id, client_id)
  where client_id is not null;

create table if not exists public.user_prayer_contents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  prayer_id bigint not null references public.user_prayers (id) on delete cascade,
  client_id text,
  content text not null default '',
  registered_at text not null default ''
);

alter table public.user_prayer_contents add column if not exists client_id text;

create index if not exists user_prayer_contents_user_id_prayer_id_idx
  on public.user_prayer_contents (user_id, prayer_id, registered_at desc, id desc);

create unique index if not exists user_prayer_contents_user_id_client_id_idx
  on public.user_prayer_contents (user_id, client_id)
  where client_id is not null;

create table if not exists public.user_bible_grass (
  user_id uuid not null references auth.users (id) on delete cascade,
  date text not null,
  data jsonb not null default '[]'::jsonb,
  primary key (user_id, date)
);

alter table public.user_bible_state enable row level security;
alter table public.user_favorite_verses enable row level security;
alter table public.user_memos enable row level security;
alter table public.user_memo_verses enable row level security;
alter table public.user_plans enable row level security;
alter table public.user_prayers enable row level security;
alter table public.user_prayer_contents enable row level security;
alter table public.user_bible_grass enable row level security;

drop policy if exists "user_bible_state_owner" on public.user_bible_state;
create policy "user_bible_state_owner"
  on public.user_bible_state
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_favorite_verses_owner" on public.user_favorite_verses;
create policy "user_favorite_verses_owner"
  on public.user_favorite_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_memos_owner" on public.user_memos;
create policy "user_memos_owner"
  on public.user_memos
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_memo_verses_owner" on public.user_memo_verses;
create policy "user_memo_verses_owner"
  on public.user_memo_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_plans_owner" on public.user_plans;
create policy "user_plans_owner"
  on public.user_plans
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_prayers_owner" on public.user_prayers;
create policy "user_prayers_owner"
  on public.user_prayers
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_prayer_contents_owner" on public.user_prayer_contents;
create policy "user_prayer_contents_owner"
  on public.user_prayer_contents
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_bible_grass_owner" on public.user_bible_grass;
create policy "user_bible_grass_owner"
  on public.user_bible_grass
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
