create table if not exists public.bible_state (
  user_id uuid primary key references auth.users (id) on delete cascade,
  app_theme text not null default 'light',
  app_language text not null default 'ko',
  bible_search_info jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.favorite_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  verse_text text not null default '',
  created_at text not null default '',
  primary key (user_id, book_code, chapter, verse)
);

create table if not exists public.memos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  title text not null default '',
  content text not null default '',
  verse_text text not null default '',
  created_at text not null default ''
);

alter table public.memos add column if not exists client_id text;

create index if not exists memos_user_id_created_at_idx
  on public.memos (user_id, created_at desc, id desc);

create unique index if not exists memos_user_id_client_id_idx
  on public.memos (user_id, client_id)
  where client_id is not null;

create table if not exists public.memo_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  memo_id bigint not null references public.memos (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  primary key (user_id, memo_id, book_code, chapter, verse)
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  plan_name text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  total_read_count integer not null default 0,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  goal_status jsonb not null default '[]'::jsonb,
  selected_book_codes jsonb not null default '[]'::jsonb,
  created_at text not null default '',
  updated_at text not null default ''
);

alter table public.plans add column if not exists client_id text;

create index if not exists plans_user_id_idx
  on public.plans (user_id, id desc);

create unique index if not exists plans_user_id_client_id_idx
  on public.plans (user_id, client_id)
  where client_id is not null;

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '',
  email text,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.churches (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid not null references auth.users (id) on delete restrict,
  super_admin_user_id uuid not null references auth.users (id) on delete restrict,
  member_count integer not null default 0,
  deputy_admin_user_ids text not null default ''
);

create index if not exists churches_name_idx
  on public.churches (name);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid not null references auth.users (id) on delete restrict,
  leader_user_id uuid references auth.users (id) on delete set null
);

create unique index if not exists teams_church_id_name_idx
  on public.teams (church_id, name);

create index if not exists teams_church_id_idx
  on public.teams (church_id, id desc);

create table if not exists public.church_memberships (
  church_id bigint not null references public.churches (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  team_id bigint references public.teams (id) on delete set null,
  joined_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (church_id, user_id),
  constraint church_memberships_role_check check (role in ('super_admin', 'deputy_admin', 'member'))
);

create index if not exists church_memberships_user_id_idx
  on public.church_memberships (user_id, joined_at desc);

create index if not exists church_memberships_church_id_team_id_idx
  on public.church_memberships (church_id, team_id);

create table if not exists public.church_join_requests (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  requester_user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'pending',
  requested_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz,
  processed_by_user_id uuid references auth.users (id) on delete set null,
  constraint church_join_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

create index if not exists church_join_requests_church_id_status_idx
  on public.church_join_requests (church_id, status, requested_at desc);

create unique index if not exists church_join_requests_pending_unique_idx
  on public.church_join_requests (church_id, requester_user_id)
  where status = 'pending';

alter table public.plans
  add column if not exists church_id bigint references public.churches (id) on delete cascade;

alter table public.plans
  add column if not exists team_id bigint references public.teams (id) on delete cascade;

create index if not exists plans_church_id_idx
  on public.plans (church_id, id desc);

create index if not exists plans_team_id_idx
  on public.plans (team_id, id desc);

create table if not exists public.plan_progresses (
  plan_id bigint not null references public.plans (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  goal_status jsonb not null default '[]'::jsonb,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (plan_id, user_id)
);

create index if not exists plan_progresses_user_id_idx
  on public.plan_progresses (user_id, updated_at desc);

create table if not exists public.church_prayers (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  team_id bigint references public.teams (id) on delete cascade,
  requester text not null default '',
  target text not null default '',
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null default '',
  updated_at text not null default ''
);

create index if not exists church_prayers_church_id_updated_at_idx
  on public.church_prayers (church_id, updated_at desc, id desc);

create index if not exists church_prayers_team_id_updated_at_idx
  on public.church_prayers (team_id, updated_at desc, id desc);

create table if not exists public.church_prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.church_prayers (id) on delete cascade,
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  content text not null default '',
  registered_at text not null default ''
);

create index if not exists church_prayer_contents_prayer_id_registered_at_idx
  on public.church_prayer_contents (prayer_id, registered_at desc, id desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.is_church_member(p_church_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
  );
$$;

create or replace function public.is_church_admin(p_church_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
      and membership.role in ('super_admin', 'deputy_admin')
  );
$$;

create or replace function public.is_church_super_admin(p_church_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
      and membership.role = 'super_admin'
  );
$$;

create or replace function public.is_plan_target_member(p_plan_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.plans plan
    join public.church_memberships membership
      on membership.church_id = plan.church_id
     and membership.user_id = p_user_id
    where plan.id = p_plan_id
      and plan.church_id is not null
      and (plan.team_id is null or membership.team_id = plan.team_id)
  );
$$;

create or replace function public.can_access_church_audience(
  p_church_id bigint,
  p_team_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_access$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
      and (
        p_team_id is null
        or membership.team_id = p_team_id
        or membership.role in ('super_admin', 'deputy_admin')
      )
  );
$church_prayer_access$;

create or replace function public.can_access_church_prayer(
  p_prayer_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_read$
  select exists (
    select 1
    from public.church_prayers prayer
    where prayer.id = p_prayer_id
      and public.can_access_church_audience(prayer.church_id, prayer.team_id, p_user_id)
  );
$church_prayer_read$;

create or replace function public.can_manage_church_prayer(
  p_prayer_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_manage$
  select exists (
    select 1
    from public.church_prayers prayer
    where prayer.id = p_prayer_id
      and (
        prayer.created_by_user_id = p_user_id
        or public.is_church_admin(prayer.church_id, p_user_id)
      )
  );
$church_prayer_manage$;

create or replace function public.can_manage_church_prayer_content(
  p_content_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_content_manage$
  select exists (
    select 1
    from public.church_prayer_contents content
    where content.id = p_content_id
      and (
        content.created_by_user_id = p_user_id
        or public.can_manage_church_prayer(content.prayer_id, p_user_id)
      )
  );
$church_prayer_content_manage$;

create or replace function public.sync_church_cached_fields(p_church_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.churches church
  set member_count = (
        select count(*)
        from public.church_memberships membership
        where membership.church_id = p_church_id
      ),
      deputy_admin_user_ids = coalesce((
        select string_agg(membership.user_id::text, ', ' order by membership.joined_at, membership.user_id::text)
        from public.church_memberships membership
        where membership.church_id = p_church_id
          and membership.role = 'deputy_admin'
      ), ''),
      updated_at = timezone('utc', now())
  where church.id = p_church_id;
end;
$$;

create or replace function public.sync_plan_progress_rows_for_plan(p_plan_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_church_id bigint;
  v_team_id bigint;
begin
  select plan.church_id, plan.team_id
  into v_church_id, v_team_id
  from public.plans plan
  where plan.id = p_plan_id;

  if v_church_id is null then
    return;
  end if;

  insert into public.plan_progresses (
    plan_id,
    user_id,
    goal_status,
    current_read_count,
    goal_percent,
    read_count_per_day,
    rest_day
  )
  select
    p_plan_id,
    membership.user_id,
    '[]'::jsonb,
    0,
    0,
    0,
    0
  from public.church_memberships membership
  where membership.church_id = v_church_id
    and (v_team_id is null or membership.team_id = v_team_id)
  on conflict (plan_id, user_id) do nothing;
end;
$$;

create or replace function public.sync_plan_progress_rows_for_member(
  p_church_id bigint,
  p_user_id uuid,
  p_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.plan_progresses (
    plan_id,
    user_id,
    goal_status,
    current_read_count,
    goal_percent,
    read_count_per_day,
    rest_day
  )
  select
    plan.id,
    p_user_id,
    '[]'::jsonb,
    0,
    0,
    0,
    0
  from public.plans plan
  where plan.church_id = p_church_id
    and (plan.team_id is null or plan.team_id = p_team_id)
  on conflict (plan_id, user_id) do nothing;
end;
$$;

create or replace function public.handle_church_membership_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.sync_church_cached_fields(old.church_id);
    return old;
  end if;

  perform public.sync_church_cached_fields(new.church_id);
  perform public.sync_plan_progress_rows_for_member(new.church_id, new.user_id, new.team_id);
  return new;
end;
$$;

create or replace function public.handle_plan_audience_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.church_id is not null then
    perform public.sync_plan_progress_rows_for_plan(new.id);
  end if;

  return new;
end;
$$;

create or replace function public.create_church(p_name text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_name text;
  v_church_id bigint;
begin
  v_user_id := auth.uid();
  v_name := trim(coalesce(p_name, ''));

  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_name = '' then
    raise exception 'CHURCH_NAME_REQUIRED';
  end if;

  insert into public.churches (
    name,
    created_by_user_id,
    super_admin_user_id
  )
  values (
    v_name,
    v_user_id,
    v_user_id
  )
  returning id into v_church_id;

  insert into public.church_memberships (
    church_id,
    user_id,
    role,
    created_by_user_id
  )
  values (
    v_church_id,
    v_user_id,
    'super_admin',
    v_user_id
  )
  on conflict (church_id, user_id) do nothing;

  perform public.sync_church_cached_fields(v_church_id);

  return v_church_id;
end;
$$;

create or replace function public.set_team_leader(
  p_team_id bigint,
  p_leader_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_church_id bigint;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select team.church_id
  into v_church_id
  from public.teams team
  where team.id = p_team_id;

  if v_church_id is null then
    raise exception 'TEAM_NOT_FOUND';
  end if;

  if not public.is_church_admin(v_church_id, v_actor_user_id) then
    raise exception 'PERMISSION_DENIED';
  end if;

  if p_leader_user_id is not null and not exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = v_church_id
      and membership.user_id = p_leader_user_id
      and membership.team_id = p_team_id
  ) then
    raise exception 'TEAM_LEADER_MUST_BE_TEAM_MEMBER';
  end if;

  update public.teams team
  set leader_user_id = p_leader_user_id
  where team.id = p_team_id;
end;
$$;

create or replace function public.set_church_member_team(
  p_church_id bigint,
  p_target_user_id uuid,
  p_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_actor_role text;
  v_target_role text;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select membership.role
  into v_actor_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = v_actor_user_id;

  if v_actor_role is null then
    raise exception 'PERMISSION_DENIED';
  end if;

  select membership.role
  into v_target_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;

  if v_target_role is null then
    raise exception 'CHURCH_MEMBER_NOT_FOUND';
  end if;

  if p_team_id is not null and not exists (
    select 1
    from public.teams team
    where team.id = p_team_id
      and team.church_id = p_church_id
  ) then
    raise exception 'TEAM_NOT_FOUND';
  end if;

  if not (
    v_actor_role = 'super_admin'
    or (v_actor_role = 'deputy_admin' and v_target_role = 'member')
  ) then
    raise exception 'PERMISSION_DENIED';
  end if;

  update public.church_memberships membership
  set team_id = p_team_id
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;
end;
$$;

create or replace function public.remove_church_member(
  p_church_id bigint,
  p_target_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_actor_role text;
  v_target_role text;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select membership.role
  into v_actor_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = v_actor_user_id;

  select membership.role
  into v_target_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;

  if v_target_role is null then
    raise exception 'CHURCH_MEMBER_NOT_FOUND';
  end if;

  if v_actor_user_id = p_target_user_id then
    if v_target_role = 'super_admin' then
      raise exception 'SUPER_ADMIN_CANNOT_LEAVE';
    end if;
  elsif not (
    v_actor_role = 'super_admin'
    or (v_actor_role = 'deputy_admin' and v_target_role = 'member')
  ) then
    raise exception 'PERMISSION_DENIED';
  elsif v_target_role = 'super_admin' then
    raise exception 'SUPER_ADMIN_CANNOT_BE_REMOVED';
  end if;

  delete from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;
end;
$$;

create or replace function public.cleanup_team_leader_on_membership_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.teams team
    set leader_user_id = null
    where team.church_id = old.church_id
      and team.leader_user_id = old.user_id;

    return old;
  end if;

  if old.team_id is distinct from new.team_id then
    update public.teams team
    set leader_user_id = null
    where team.church_id = old.church_id
      and team.id = old.team_id
      and team.leader_user_id = old.user_id;
  end if;

  return new;
end;
$$;

create or replace function public.validate_church_prayer_team_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $church_prayer_validate$
begin
  if new.team_id is not null and not exists (
    select 1
    from public.teams team
    where team.id = new.team_id
      and team.church_id = new.church_id
  ) then
    raise exception 'INVALID_PRAYER_TEAM_SCOPE';
  end if;

  return new;
end;
$church_prayer_validate$;

create or replace function public.sync_church_prayer_updated_at_from_content()
returns trigger
language plpgsql
security definer
set search_path = public
as $church_prayer_touch$
declare
  v_prayer_id bigint;
begin
  v_prayer_id := case when tg_op = 'DELETE' then old.prayer_id else new.prayer_id end;

  update public.church_prayers prayer
  set updated_at = to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')
  where prayer.id = v_prayer_id;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$church_prayer_touch$;

revoke all on function public.create_church(text) from public;
grant execute on function public.create_church(text) to authenticated;
revoke all on function public.set_team_leader(bigint, uuid) from public;
grant execute on function public.set_team_leader(bigint, uuid) to authenticated;
revoke all on function public.set_church_member_team(bigint, uuid, bigint) from public;
grant execute on function public.set_church_member_team(bigint, uuid, bigint) to authenticated;
revoke all on function public.remove_church_member(bigint, uuid) from public;
grant execute on function public.remove_church_member(bigint, uuid) to authenticated;

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists churches_set_updated_at on public.churches;
create trigger churches_set_updated_at
before update on public.churches
for each row
execute function public.touch_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row
execute function public.touch_updated_at();

drop trigger if exists church_memberships_set_updated_at on public.church_memberships;
create trigger church_memberships_set_updated_at
before update on public.church_memberships
for each row
execute function public.touch_updated_at();

drop trigger if exists church_memberships_cleanup_team_leader on public.church_memberships;
create trigger church_memberships_cleanup_team_leader
after update of team_id or delete on public.church_memberships
for each row
execute function public.cleanup_team_leader_on_membership_change();

drop trigger if exists plan_progresses_set_updated_at on public.plan_progresses;
create trigger plan_progresses_set_updated_at
before update on public.plan_progresses
for each row
execute function public.touch_updated_at();

drop trigger if exists church_prayers_validate_team_scope on public.church_prayers;
create trigger church_prayers_validate_team_scope
before insert or update on public.church_prayers
for each row
execute function public.validate_church_prayer_team_scope();

drop trigger if exists church_prayer_contents_sync_updated_at on public.church_prayer_contents;
create trigger church_prayer_contents_sync_updated_at
after insert or update or delete on public.church_prayer_contents
for each row
execute function public.sync_church_prayer_updated_at_from_content();

drop trigger if exists church_memberships_after_write_sync on public.church_memberships;
create trigger church_memberships_after_write_sync
after insert or update or delete on public.church_memberships
for each row
execute function public.handle_church_membership_change();

drop trigger if exists plans_after_write_sync_progress on public.plans;
create trigger plans_after_write_sync_progress
after insert or update of church_id, team_id on public.plans
for each row
execute function public.handle_plan_audience_change();

create table if not exists public.prayers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  requester text not null default '',
  target text not null default '',
  created_at text not null default ''
);

alter table public.prayers add column if not exists client_id text;

create unique index if not exists prayers_user_id_client_id_idx
  on public.prayers (user_id, client_id)
  where client_id is not null;

create table if not exists public.prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.prayers (id) on delete cascade,
  client_id text,
  content text not null default '',
  registered_at text not null default ''
);

alter table public.prayer_contents add column if not exists client_id text;

drop index if exists public.prayer_contents_user_id_prayer_id_idx;
drop index if exists public.prayer_contents_user_id_client_id_idx;

create index if not exists prayer_contents_prayer_id_registered_at_idx
  on public.prayer_contents (prayer_id, registered_at desc, id desc);

create unique index if not exists prayer_contents_prayer_id_client_id_idx
  on public.prayer_contents (prayer_id, client_id)
  where client_id is not null;

create table if not exists public.bible_grass (
  user_id uuid not null references auth.users (id) on delete cascade,
  date text not null,
  data jsonb not null default '[]'::jsonb,
  primary key (user_id, date)
);

alter table public.bible_state enable row level security;
alter table public.favorite_verses enable row level security;
alter table public.memos enable row level security;
alter table public.memo_verses enable row level security;
alter table public.plans enable row level security;
alter table public.user_profiles enable row level security;
alter table public.churches enable row level security;
alter table public.teams enable row level security;
alter table public.church_memberships enable row level security;
alter table public.church_join_requests enable row level security;
alter table public.plan_progresses enable row level security;
alter table public.church_prayers enable row level security;
alter table public.church_prayer_contents enable row level security;
alter table public.prayers enable row level security;
alter table public.prayer_contents enable row level security;
alter table public.bible_grass enable row level security;

drop policy if exists "bible_state_owner" on public.bible_state;
create policy "bible_state_owner"
  on public.bible_state
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "favorite_verses_owner" on public.favorite_verses;
create policy "favorite_verses_owner"
  on public.favorite_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memos_owner" on public.memos;
create policy "memos_owner"
  on public.memos
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memo_verses_owner" on public.memo_verses;
create policy "memo_verses_owner"
  on public.memo_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "plans_owner" on public.plans;
drop policy if exists "plans_select_access" on public.plans;
drop policy if exists "plans_insert_access" on public.plans;
drop policy if exists "plans_update_access" on public.plans;
drop policy if exists "plans_delete_access" on public.plans;
create policy "plans_select_access"
  on public.plans
  for select
  using (
    auth.uid() = user_id
    or (
      church_id is not null
      and public.is_church_member(church_id, auth.uid())
    )
  );
create policy "plans_insert_access"
  on public.plans
  for insert
  with check (
    auth.uid() = user_id
    and (
      (church_id is null and team_id is null)
      or (
        church_id is not null
        and (
          public.is_church_super_admin(church_id, auth.uid())
          or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
        )
      )
    )
  );
create policy "plans_update_access"
  on public.plans
  for update
  using (
    (church_id is null and auth.uid() = user_id)
    or (
      church_id is not null
      and (
        public.is_church_super_admin(church_id, auth.uid())
        or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
      )
    )
  )
  with check (
    (church_id is null and auth.uid() = user_id)
    or (
      church_id is not null
      and (
        public.is_church_super_admin(church_id, auth.uid())
        or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
      )
    )
  );
create policy "plans_delete_access"
  on public.plans
  for delete
  using (
    (church_id is null and auth.uid() = user_id)
    or (
      church_id is not null
      and (
        public.is_church_super_admin(church_id, auth.uid())
        or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
      )
    )
  );

drop policy if exists "user_profiles_read_authenticated" on public.user_profiles;
drop policy if exists "user_profiles_self_insert" on public.user_profiles;
drop policy if exists "user_profiles_self_update" on public.user_profiles;
drop policy if exists "user_profiles_self_delete" on public.user_profiles;
create policy "user_profiles_read_authenticated"
  on public.user_profiles
  for select
  using (auth.role() = 'authenticated');
create policy "user_profiles_self_insert"
  on public.user_profiles
  for insert
  with check (auth.uid() = user_id);
create policy "user_profiles_self_update"
  on public.user_profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "user_profiles_self_delete"
  on public.user_profiles
  for delete
  using (auth.uid() = user_id);

drop policy if exists "churches_read_authenticated" on public.churches;
drop policy if exists "churches_update_super_admin" on public.churches;
create policy "churches_read_authenticated"
  on public.churches
  for select
  using (auth.role() = 'authenticated');
create policy "churches_update_super_admin"
  on public.churches
  for update
  using (public.is_church_super_admin(id, auth.uid()))
  with check (public.is_church_super_admin(id, auth.uid()));

drop policy if exists "teams_read_members" on public.teams;
drop policy if exists "teams_manage_admins" on public.teams;
create policy "teams_read_members"
  on public.teams
  for select
  using (public.is_church_member(church_id, auth.uid()));
create policy "teams_manage_admins"
  on public.teams
  for all
  using (public.is_church_admin(church_id, auth.uid()))
  with check (public.is_church_admin(church_id, auth.uid()));

drop policy if exists "church_memberships_read_members" on public.church_memberships;
drop policy if exists "church_memberships_insert_admins" on public.church_memberships;
drop policy if exists "church_memberships_update_super_admin" on public.church_memberships;
drop policy if exists "church_memberships_delete_super_admin" on public.church_memberships;
create policy "church_memberships_read_members"
  on public.church_memberships
  for select
  using (
    auth.uid() = user_id
    or public.is_church_member(church_id, auth.uid())
  );
create policy "church_memberships_insert_admins"
  on public.church_memberships
  for insert
  with check (
    public.is_church_admin(church_id, auth.uid())
    and auth.uid() = created_by_user_id
  );
create policy "church_memberships_update_super_admin"
  on public.church_memberships
  for update
  using (public.is_church_super_admin(church_id, auth.uid()))
  with check (public.is_church_super_admin(church_id, auth.uid()));
create policy "church_memberships_delete_super_admin"
  on public.church_memberships
  for delete
  using (public.is_church_super_admin(church_id, auth.uid()));

drop policy if exists "church_join_requests_select_access" on public.church_join_requests;
drop policy if exists "church_join_requests_insert_self" on public.church_join_requests;
drop policy if exists "church_join_requests_update_admins" on public.church_join_requests;
create policy "church_join_requests_select_access"
  on public.church_join_requests
  for select
  using (
    requester_user_id = auth.uid()
    or public.is_church_admin(church_id, auth.uid())
  );
create policy "church_join_requests_insert_self"
  on public.church_join_requests
  for insert
  with check (
    requester_user_id = auth.uid()
    and auth.role() = 'authenticated'
  );
create policy "church_join_requests_update_admins"
  on public.church_join_requests
  for update
  using (public.is_church_admin(church_id, auth.uid()))
  with check (public.is_church_admin(church_id, auth.uid()));

drop policy if exists "plan_progresses_select_access" on public.plan_progresses;
drop policy if exists "plan_progresses_update_self" on public.plan_progresses;
create policy "plan_progresses_select_access"
  on public.plan_progresses
  for select
  using (
    auth.uid() = user_id
    or exists (
      select 1
      from public.plans plan
      where plan.id = plan_progresses.plan_id
        and plan.church_id is not null
        and public.is_church_member(plan.church_id, auth.uid())
    )
  );
create policy "plan_progresses_update_self"
  on public.plan_progresses
  for update
  using (
    auth.uid() = user_id
    and public.is_plan_target_member(plan_id, auth.uid())
  )
  with check (
    auth.uid() = user_id
    and public.is_plan_target_member(plan_id, auth.uid())
  );

drop policy if exists "church_prayers_select_access" on public.church_prayers;
drop policy if exists "church_prayers_insert_access" on public.church_prayers;
drop policy if exists "church_prayers_update_manage" on public.church_prayers;
drop policy if exists "church_prayers_delete_manage" on public.church_prayers;
create policy "church_prayers_select_access"
  on public.church_prayers
  for select
  using (public.can_access_church_audience(church_id, team_id, auth.uid()));
create policy "church_prayers_insert_access"
  on public.church_prayers
  for insert
  with check (
    created_by_user_id = auth.uid()
    and public.can_access_church_audience(church_id, team_id, auth.uid())
  );
create policy "church_prayers_update_manage"
  on public.church_prayers
  for update
  using (public.can_manage_church_prayer(id, auth.uid()))
  with check (
    public.can_manage_church_prayer(id, auth.uid())
    and public.can_access_church_audience(church_id, team_id, auth.uid())
  );
create policy "church_prayers_delete_manage"
  on public.church_prayers
  for delete
  using (public.can_manage_church_prayer(id, auth.uid()));

drop policy if exists "church_prayer_contents_select_access" on public.church_prayer_contents;
drop policy if exists "church_prayer_contents_insert_access" on public.church_prayer_contents;
drop policy if exists "church_prayer_contents_update_manage" on public.church_prayer_contents;
drop policy if exists "church_prayer_contents_delete_manage" on public.church_prayer_contents;
create policy "church_prayer_contents_select_access"
  on public.church_prayer_contents
  for select
  using (public.can_access_church_prayer(prayer_id, auth.uid()));
create policy "church_prayer_contents_insert_access"
  on public.church_prayer_contents
  for insert
  with check (
    created_by_user_id = auth.uid()
    and public.can_access_church_prayer(prayer_id, auth.uid())
  );
create policy "church_prayer_contents_update_manage"
  on public.church_prayer_contents
  for update
  using (public.can_manage_church_prayer_content(id, auth.uid()))
  with check (public.can_manage_church_prayer_content(id, auth.uid()));
create policy "church_prayer_contents_delete_manage"
  on public.church_prayer_contents
  for delete
  using (public.can_manage_church_prayer_content(id, auth.uid()));

drop policy if exists "prayers_owner" on public.prayers;
create policy "prayers_owner"
  on public.prayers
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "prayer_contents_owner" on public.prayer_contents;
create policy "prayer_contents_owner"
  on public.prayer_contents
  for all
  using (
    exists (
      select 1
      from public.prayers
      where prayers.id = prayer_contents.prayer_id
        and prayers.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.prayers
      where prayers.id = prayer_contents.prayer_id
        and prayers.user_id = auth.uid()
    )
  );

drop policy if exists "bible_grass_owner" on public.bible_grass;
create policy "bible_grass_owner"
  on public.bible_grass
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
