export type BibleCategoryKey =
  | 'ot'
  | 'nt'
  | 'pentateuch'
  | 'history'
  | 'poetry'
  | 'prophecy'
  | 'gospels'
  | 'epistles';

export const BIBLE_CATEGORY_KEYS: BibleCategoryKey[] = [
  'ot',
  'nt',
  'pentateuch',
  'history',
  'poetry',
  'prophecy',
  'gospels',
  'epistles',
];

export const CATEGORY_BOOK_CODES: Record<BibleCategoryKey, string[]> = {
  ot: [
    'genesis',
    'exodus',
    'leviticus',
    'numbers',
    'deuteronomy',
    'joshua',
    'judges',
    'ruth',
    '1samuel',
    '2samuel',
    '1kings',
    '2kings',
    '1chronicles',
    '2chronicles',
    'ezra',
    'nehemiah',
    'esther',
    'job',
    'psalms',
    'proverbs',
    'ecclesiastes',
    'songofsolomon',
    'isaiah',
    'jeremiah',
    'lamentations',
    'ezekiel',
    'daniel',
    'hosea',
    'joel',
    'amos',
    'obadiah',
    'jonah',
    'micah',
    'nahum',
    'habakkuk',
    'zephaniah',
    'haggai',
    'zechariah',
    'malachi',
  ],
  nt: [
    'matthew',
    'mark',
    'luke',
    'john',
    'acts',
    'romans',
    '1corinthians',
    '2corinthians',
    'galatians',
    'ephesians',
    'philippians',
    'colossians',
    '1thessalonians',
    '2thessalonians',
    '1timothy',
    '2timothy',
    'titus',
    'philemon',
    'hebrews',
    'james',
    '1peter',
    '2peter',
    '1john',
    '2john',
    '3john',
    'jude',
    'revelation',
  ],
  pentateuch: ['genesis', 'exodus', 'leviticus', 'numbers', 'deuteronomy'],
  history: [
    'joshua',
    'judges',
    'ruth',
    '1samuel',
    '2samuel',
    '1kings',
    '2kings',
    '1chronicles',
    '2chronicles',
    'ezra',
    'nehemiah',
    'esther',
  ],
  poetry: ['job', 'psalms', 'proverbs', 'ecclesiastes', 'songofsolomon'],
  prophecy: [
    'isaiah',
    'jeremiah',
    'lamentations',
    'ezekiel',
    'daniel',
    'hosea',
    'joel',
    'amos',
    'obadiah',
    'jonah',
    'micah',
    'nahum',
    'habakkuk',
    'zephaniah',
    'haggai',
    'zechariah',
    'malachi',
  ],
  gospels: ['matthew', 'mark', 'luke', 'john'],
  epistles: [
    'acts',
    'romans',
    '1corinthians',
    '2corinthians',
    'galatians',
    'ephesians',
    'philippians',
    'colossians',
    '1thessalonians',
    '2thessalonians',
    '1timothy',
    '2timothy',
    'titus',
    'philemon',
    'hebrews',
    'james',
    '1peter',
    '2peter',
    '1john',
    '2john',
    '3john',
    'jude',
    'revelation',
  ],
};
